10 REM Billboard
20 REM All input must be in upper case
30 CLS
40 INPUT "Enter your message ", A$
50 B = LEN(A$)
60 FOR C = 1 TO B
70 D = ASC(MID$(A$, C)) - 64
80 IF D = -18 THEN GOSUB 410: GOTO 130: REM Period (.)
90 IF D = -31 THEN GOSUB 420: GOTO 130: REM Exclamation mark (!)
100 IF D = -32 THEN GOSUB 430: GOTO 130: REM Space
110 IF D < 1 OR D > 26 THEN GOSUB 430: GOTO 130: REM UNKNOWN CHARACTER
120 ON D GOSUB 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400
130 LPRINT: NEXT C
140 END
150 LPRINT "AAAAA  ": LPRINT "   A A ": LPRINT "   A  A": LPRINT "   A A ": LPRINT "AAAAA  ": RETURN
160 LPRINT "BBBBBBB": LPRINT "B  B  B": LPRINT "B  B  B": LPRINT "B  B  B": LPRINT " BB BB ": RETURN
170 LPRINT " CCCCC ": LPRINT "C     C": LPRINT "C     C": LPRINT "C     C": LPRINT " C   C ": RETURN
180 LPRINT "DDDDDDD": LPRINT "D     D": LPRINT "D     D": LPRINT "D     D": LPRINT " DDDDD ": RETURN
190 LPRINT "EEEEEEE": LPRINT "E  E  E": LPRINT "E  E  E": LPRINT "E     E": LPRINT "E      ": RETURN
200 LPRINT "FFFFFFF": LPRINT "   F  F": LPRINT "   F  F": LPRINT "   F  F": LPRINT "      F": RETURN
210 LPRINT " GGGGG ": LPRINT "G     G": LPRINT "G     G": LPRINT "G G   G": LPRINT " GG  G ": RETURN
220 LPRINT "HHHHHHH": LPRINT "   H   ": LPRINT "   H   ": LPRINT "   H   ": LPRINT "HHHHHHH": RETURN
230 LPRINT "       ": LPRINT "I     I": LPRINT "IIIIIII": LPRINT "I     I": LPRINT "       ": RETURN
240 LPRINT "       ": LPRINT "JJJ    ": LPRINT "J     J": LPRINT "J     J": LPRINT " JJJJJJ": RETURN
250 LPRINT "KKKKKKK": LPRINT "   K   ": LPRINT "  K K  ": LPRINT " K   K ": LPRINT "K     K": RETURN
260 LPRINT "LLLLLLL": LPRINT "L      ": LPRINT "L      ": LPRINT "L      ": LPRINT "L      ": RETURN
270 LPRINT "MMMMMMM": LPRINT "     M ": LPRINT "   MM  ": LPRINT "     M ": LPRINT "MMMMMMM": RETURN
280 LPRINT "NNNNNNN": LPRINT "     NN": LPRINT "   NN  ": LPRINT " NN    ": LPRINT "NNNNNNN": RETURN
290 LPRINT " OOOOO ": LPRINT "O     O": LPRINT "O     O": LPRINT "O     O": LPRINT " OOOOO ": RETURN
300 LPRINT "PPPPPP ": LPRINT "   P  P": LPRINT "   P  P": LPRINT "   P  P": LPRINT "    PP ": RETURN
310 LPRINT " QQQQQ ": LPRINT "Q     Q": LPRINT "Q Q   Q": LPRINT "QQ    Q": LPRINT " QQQQQ ": RETURN
320 LPRINT "RRRRRR ": LPRINT "   R  R": LPRINT "  RR  R": LPRINT " R R  R": LPRINT "R    RR": RETURN
330 LPRINT " S  SS ": LPRINT "S  S  S": LPRINT "S  S  S": LPRINT "S  S  S": LPRINT " SS  S ": RETURN
340 LPRINT "      T": LPRINT "      T": LPRINT "TTTTTTT": LPRINT "      T": LPRINT "      T": RETURN
350 LPRINT " UUUUUU": LPRINT "U      ": LPRINT "U      ": LPRINT "U      ": LPRINT " UUUUUU": RETURN
360 LPRINT "   VVVV": LPRINT " VV    ": LPRINT "V      ": LPRINT " VV    ": LPRINT "   VVVV": RETURN
370 LPRINT " WWWWWW": LPRINT "W      ": LPRINT "WWWWW  ": LPRINT "W      ": LPRINT " WWWWWW": RETURN
380 LPRINT "X     X": LPRINT " XX XX ": LPRINT "   X   ": LPRINT " XX XX ": LPRINT "X     X": RETURN
390 LPRINT "     YY": LPRINT "    Y  ": LPRINT "YYYY   ": LPRINT "    Y  ": LPRINT "     YY": RETURN
400 LPRINT "ZZ    Z": LPRINT "Z Z   Z": LPRINT "Z  Z  Z": LPRINT "Z   Z Z": LPRINT "Z    ZZ": RETURN
410 LPRINT "@@": LPRINT "@@": LPRINT: LPRINT: LPRINT: RETURN
420 LPRINT "@@ @@@@": LPRINT "@@ @@@@": LPRINT: LPRINT: LPRINT: RETURN
430 LPRINT: LPRINT: RETURN

