10 REM Billboard
20 REM All input must be in upper case
30 CLS: COLOR 15
40 COLOR 10: INPUT "Enter your message"; A$: COLOR 15: CLS
50 B = LEN(A$)
60 FOR C = 1 TO B
65 COLOR 9 + INT(RND * 7)
70 D = ASC(MID$(A$, C)) - 64
75 IF D > 32 THEN D = D - 32
80 IF D = -18 THEN GOSUB 410: GOTO 130: REM Period (.)
90 IF D = -31 THEN GOSUB 420: GOTO 130: REM Exclamation mark (!)
100 IF D = -32 THEN GOSUB 430: GOTO 130: REM Space
110 IF D < 1 OR D > 26 THEN GOSUB 430: GOTO 130: REM UNKNOWN CHARACTER
120 ON D GOSUB 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400
125 XX = 0.5: GOSUB 1000
130 PRINT: NEXT C: COLOR 15
140 END
150 PRINT "AAAAA  ": PRINT "   A A ": PRINT "   A  A": PRINT "   A A ": PRINT "AAAAA  ": RETURN
160 PRINT "BBBBBBB": PRINT "B  B  B": PRINT "B  B  B": PRINT "B  B  B": PRINT " BB BB ": RETURN
170 PRINT " CCCCC ": PRINT "C     C": PRINT "C     C": PRINT "C     C": PRINT " C   C ": RETURN
180 PRINT "DDDDDDD": PRINT "D     D": PRINT "D     D": PRINT "D     D": PRINT " DDDDD ": RETURN
190 PRINT "EEEEEEE": PRINT "E  E  E": PRINT "E  E  E": PRINT "E     E": PRINT "E      ": RETURN
200 PRINT "FFFFFFF": PRINT "   F  F": PRINT "   F  F": PRINT "   F  F": PRINT "      F": RETURN
210 PRINT " GGGGG ": PRINT "G     G": PRINT "G     G": PRINT "G G   G": PRINT " GG  G ": RETURN
220 PRINT "HHHHHHH": PRINT "   H   ": PRINT "   H   ": PRINT "   H   ": PRINT "HHHHHHH": RETURN
230 PRINT "       ": PRINT "I     I": PRINT "IIIIIII": PRINT "I     I": PRINT "       ": RETURN
240 PRINT "       ": PRINT "JJJ    ": PRINT "J     J": PRINT "J     J": PRINT " JJJJJJ": RETURN
250 PRINT "KKKKKKK": PRINT "   K   ": PRINT "  K K  ": PRINT " K   K ": PRINT "K     K": RETURN
260 PRINT "LLLLLLL": PRINT "L      ": PRINT "L      ": PRINT "L      ": PRINT "L      ": RETURN
270 PRINT "MMMMMMM": PRINT "     M ": PRINT "   MM  ": PRINT "     M ": PRINT "MMMMMMM": RETURN
280 PRINT "NNNNNNN": PRINT "     NN": PRINT "   NN  ": PRINT " NN    ": PRINT "NNNNNNN": RETURN
290 PRINT " OOOOO ": PRINT "O     O": PRINT "O     O": PRINT "O     O": PRINT " OOOOO ": RETURN
300 PRINT "PPPPPP ": PRINT "   P  P": PRINT "   P  P": PRINT "   P  P": PRINT "    PP ": RETURN
310 PRINT " QQQQQ ": PRINT "Q     Q": PRINT "Q Q   Q": PRINT "QQ    Q": PRINT " QQQQQ ": RETURN
320 PRINT "RRRRRR ": PRINT "   R  R": PRINT "  RR  R": PRINT " R R  R": PRINT "R    RR": RETURN
330 PRINT " S  SS ": PRINT "S  S  S": PRINT "S  S  S": PRINT "S  S  S": PRINT " SS  S ": RETURN
340 PRINT "      T": PRINT "      T": PRINT "TTTTTTT": PRINT "      T": PRINT "      T": RETURN
350 PRINT " UUUUUU": PRINT "U      ": PRINT "U      ": PRINT "U      ": PRINT " UUUUUU": RETURN
360 PRINT "   VVVV": PRINT " VV    ": PRINT "V      ": PRINT " VV    ": PRINT "   VVVV": RETURN
370 PRINT " WWWWWW": PRINT "W      ": PRINT "WWWWW  ": PRINT "W      ": PRINT " WWWWWW": RETURN
380 PRINT "X     X": PRINT " XX XX ": PRINT "   X   ": PRINT " XX XX ": PRINT "X     X": RETURN
390 PRINT "     YY": PRINT "    Y  ": PRINT "YYYY   ": PRINT "    Y  ": PRINT "     YY": RETURN
400 PRINT "ZZ    Z": PRINT "Z Z   Z": PRINT "Z  Z  Z": PRINT "Z   Z Z": PRINT "Z    ZZ": RETURN
410 PRINT "@@": PRINT "@@": PRINT: PRINT: PRINT: RETURN
420 PRINT "@@ @@@@": PRINT "@@ @@@@": PRINT: PRINT: PRINT: RETURN
430 PRINT: PRINT: RETURN
1000 ST = TIMER + XX
1010 IF TIMER < ST THEN 1010
1020 RETURN

