
10 'STATES AND CAPITALS 
20 ' CHUCK FAESSLER FEB 1983
25 ' 617 CAMERON COURT
26 ' KENNER,LA. 70062
30 CLS:CLEAR 1000
40 DIM A$(50),B$(50)
50 FOR I=1 TO 50 
60 READ A$(I),B$(I):NEXT I
70 PRINT@1,"**** STATES AND CAPITALS ****"
80 PRINT@68,"THIS PROGRAM WILL TEST YOUR  KNOWLEDGE OF THE 50 STATES AND CAPITALS. AFTER EACH STATE (SELECTED AT RANDOM) TYPE ITS CAPITAL FOLLOWED BY <ENTER>"
90 N=0:C=0:W=0:X=0
100 N=N+1:IF N>10 THEN 260
110 I=RND(50)
120 IF X=I THEN GOTO110
130 X=I
140 Q=0
150 PRINT"":PRINT"     WHAT IS THE CAPITAL OF      ";A$(I);:INPUT Z$
160 IF Z$=B$(I) THEN 190
170 PRINT"":PRINT" NOT CORRECT!...TRY AGAIN":W=W+1
180 Q=Q+1:IF Q>=2 THEN 370 ELSE 150
190 R=RND(5):C=C+1:PRINT""
200 IF R=1 THEN 210:IF R=2 THEN 290:IF R=3 THEN 230:IF R=4 THEN 240:IF R=5 THEN 250
210 PRINT" CORRECT...YOU'RE A GENIUS!!":GOTO100
220 PRINT" CORRECT...YOU'RE EXCEPTIONAL!!":GOTO100
230 PRINT" CORRECT...AMAZING ABILITY!!":GOTO100
240 PRINT" CORRECT...YOU'RE TOO MUCH!!":GOTO100
250 PRINT" RIGHT ON...CARRY ON!!":GOTO100
260 T=C+W
270 CLS:PRINT@6,"**** YOUR SCORE ****"
280 PRINT@64,C;"CORRECT";W;"WRONG";" GRADE"INT(C/T*100);
290 PRINT"%"
300 PRINT@290,"DO YOU WISH TO CONTINUE":PRINT@ 325,"<ENTER> YES OR NO":PRINT"":INPUT C$
310 CLS:IF C$="YES" THEN 90 ELSE 410
320 DATA MASSACHUSETTS,BOSTON,MAINE,AUGUSTA,VERMONT,MONTPELIER,NEVADA,CARSON CITY,NEW HAMPSHIRE,CONCORD,NEW YORK,ALBANY,NEW JERSEY,TRENTON,CONNECTICUT,HARTFORD,VIRGINIA,RICHMOND,WEST VIRGINIA,CHARLESTON,MARYLAND,ANNAPOLIS,NORTH CAROLINA,RALEIGH
330 DATA SOUTH CAROLINA,COLUMBIA,FLORIDA,TALLAHASSEE,GEORGIA,ATLANTA,ALABAMA,MONTGOMERY,ARKANSAS,LITTLE ROCK,MISSISSIPPI,JACKSON,WASHINGTON,OLYMPIA,NEW MEXICO,SANTA FE,NORTH DAKOTA,BISMARK,SOUTH DAKOTA,PIERRE,IDAHO,BOISE,ILLINOIS,SPRINGFIELD
340 DATA OHIO,COLUMBUS,INDIANA,INDIANAPOLIS,IOWA,DES MOINES,KANSAS,TOPEKA,MISSOURI,JEFFERSON CITY,OKLAHOMA,OKLAHOMA CITY,COLORADO,DENVER,UTAH,SALT LAKE CITY,HAWAII,HONOLULU,ALASKA,JUNEAU,TEXAS,AUSTIN,LOUISIANA,BATON ROUGE
350 DATA PENNSYLVANIA,HARRISBURG,RHODE ISLAND,PROVIDENCE,WISCONSIN,MADISON,MINNESOTA,ST PAUL,MICHIGAN,LANSING,KENTUCKY,FRANKFORT,TENNESSEE,NASHVILLE,NEBRASKA,LINCOLN
360 DATA MONTANA,HELENA,WYOMING,CHEYENNE,DELAWARE,DOVER,CALIFORNIA,SACRAMENTO,OREGON,SALEM,ARIZONA,PHOENIX
370 PRINT"":PRINT"":PRINT" WELL,I GUESS YOU REALLY DON'T       KNOW IT!!(SHAME)"
380 PRINT"     THE CORRECT ANSWER IS        ";B$(I)
390 PRINT"":PRINT" NOW I WILL ASK YOU AGAIN!"
400 GOTO140
410 END
