10 REM AMANUENSIS
20 CLS
30 DIM A$(12)
40 N = 0
50 PRINT "PRESS ANY KEY TO BEGIN"
60 N = N + 1: IF INKEY$ = "" THEN 60
70 RANDOMIZE N: CLS
80 REM ****************************
90 RESTORE 330: GOSUB 450: A$(1) = B$
100 RESTORE 340: GOSUB 450: A$(2) = B$
110 RESTORE 350: GOSUB 450: A$(3) = B$
120 RESTORE 360: GOSUB 450: A$(4) = B$
130 RESTORE 370: GOSUB 450: A$(5) = B$
140 RESTORE 380: GOSUB 450: A$(6) = B$
150 RESTORE 390: GOSUB 450: A$(7) = B$
160 RESTORE 400: GOSUB 450: A$(8) = B$
170 RESTORE 410: GOSUB 450: A$(9) = B$
180 RESTORE 420: GOSUB 450: A$(10) = B$
190 RESTORE 430: GOSUB 450: A$(11) = B$
200 RESTORE 420: GOSUB 450: A$(12) = B$
210 REM ****************************
220 PRINT "THE "; A$(1); " "; A$(2); " "; A$(3)
230 PRINT "     IN THE "; A$(4); "..."
240 PRINT A$(S); " FOR "; A$(6); ","
250 PRINT "   TO "; A$(7); " THE "; A$(8); "..."
260 PRINT " "; A$(9); ", THEN "; A$(10)
270 PRINT "    ..."; A$(11); ", "; A$(12); "."
280 PRINT: PRINT
290 REM ****************************
300 IF INKEY$ = "" THEN 300
310 GOTO 90
320 REM ****************************
330 DATA "APPLICANT","SUPPLICANT","MENDICANT","BEGGAR","ASPIRANT","CLAIMANT","POSTULANT","CONVOY","SENTINEL","CASTELLAN"
340 DATA "ENTREATED","BESEECHED","WAITED","BESOUGHT","CONJURED","PRESSED","URGED","CRAVED","DEMANDED","CLAIMED"
350 DATA "SUCCESSFULLY","COURAGEOUSLY","PROGRESSIVELY","FOOLISHLY","ENDLESSLY","HELPLESSLY","HALTINGLY","SLAVISHLY","NEGLECTFULLY","PRIDEFULLY"
360 DATA "FIELD","BATTLEFIELD","PLAYGROUND","CIRCUS RING","BEAR GARDEN","ENEMY'S CAMP","HIPPODROME","THEATRE OF WAR","COURT","RACECOURSE"
370 DATA "WAITING","ASKING","HOPING","WATCHING","PRAYING","STAYING","SCREAMING","WANTING","STARING","CRYING"
380 DATA "THE FATES","FORTUNE'S WHEEL","HOBSON'S CHOICE","THE STARS","AN ASTRAL INFLUENCE","A BLIND BARGAIN","A SPELLBINDER","A MALEVOLENT SPIRIT","A ZEALOT","A DOGMATIST"
390 DATA "QUENCH","RECANT","FORSWEAR","ABJURE","RENOUNCE","RELINQUISH","WAVER","DEMUR","SWERVE","BACK"
400 DATA "GHOST","SPECTRE","HOBGOBLIN","DJINN","LEPRECHAUN","PIXIE","FAUN","SATYR","DRYAD","NAIAD"
410 DATA "WASTING","SPENDING","USING","CONSUMING","RUNNING OUT","DRYING UP","EMPTYING","EXHAUSTING","SQUANDERING","DISPENSING WITH"
420 DATA "CORRODING","ERODING","BLIGHTING","ROTTING","GNAWING","UNDERMINING","SHAKING","BREAKING","DAMAGING","WOUNDING"
430 DATA "RESTRAINING","COERCING","CHECKING","DETAINING","ENCLOSING","IMPOUNDING","HANDCUFFING","MUZZLING","GAGGING","SUPPRESSING"
440 REM ****************************
450 FOR N = 1 TO RND * 10 + 1
460 READ B$
470 NEXT N
480 RETURN

